# Generated by Django 3.0.6 on 2020-07-17 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('izin', '0002_auto_20200717_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permission',
            old_name='accepts',
            new_name='accept',
        ),
        migrations.RenameField(
            model_name='permission',
            old_name='vetos',
            new_name='veto',
        ),
    ]
