# Generated by Django 3.0.6 on 2020-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotograflar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Başlık')),
                ('date', models.DateTimeField(verbose_name='Tarih')),
                ('image', models.ImageField(blank=True, upload_to='img/', verbose_name='Fotoğraflar')),
                ('slug', models.SlugField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fotoğraflar',
            },
        ),
    ]
