# Generated by Django 2.1.15 on 2020-07-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fotograflar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Başlık')),
                ('date', models.DateTimeField(verbose_name='Tarih')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Fotoğraflar')),
                ('slug', models.SlugField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Fotoğraflar',
            },
        ),
        migrations.CreateModel(
            name='FotoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('arsiv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fotografarsivi.Fotograflar')),
            ],
        ),
    ]
