# Generated by Django 3.0.6 on 2020-07-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fotografarsivi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotograflar',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Fotoğraflar'),
        ),
        migrations.CreateModel(
            name='FotoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('arsiv', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fotografarsivi.Fotograflar')),
            ],
        ),
    ]
