# Generated by Django 3.0.6 on 2020-07-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Odevler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Ödev Adı')),
                ('date', models.DateTimeField(verbose_name='Tarih')),
                ('file', models.FileField(upload_to='media/odev-arsiv', verbose_name='Dosya')),
                ('slug', models.SlugField(max_length=100)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ödevler',
            },
        ),
    ]
