# Generated by Django 3.0.6 on 2020-07-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ödevarsivi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odevler',
            name='file',
            field=models.FileField(upload_to='pdf/odev-arsiv', verbose_name='Dosya'),
        ),
    ]
